### ISSUE TITLE
1.2 Projected debt outflows from developing countries

### ISSUE THREAD

**Issue by jm-rivera** [ONEcampaign/net_flows#7]
A chart which shows the trends in debt service repayments, but which makes a point highlighting how the problem will only get worse in the coming years.

[This chart](https://data.one.org/topics/african-debt/#african-countries-are-set-to-pay-record-amounts-in-debt-service-in-the-coming-years) is a good example of what the data shows. The focus would be on 'all developing countries', though we could enable some exploration (of 'africa' for example), via a dropdown.

The goal of the chart(s) is to show the trend and how it is getting worse.

A key part of this story is the role of China. We may need two separate charts:
- One chart like the example, which is making the point of increasing repayments.
- A separate chart which is specifically highlighting the role of Chinese debt in that story.

**Comment by lpicci96** [comment]
explore slope charts, faceted or not faceted or scrolly. Advantage of slope is more easily isolate changes in individual categories. But potentially problematic for different scales/magnitudes eg "total"

**Comment by jm-rivera** [comment]
Two options for this.

[**Option 1**](https://public.flourish.studio/visualisation/17498076/): a classic time series as a stacked column broken down by type.

![image](https://github.com/ONEcampaign/net_flows/assets/7374450/b5f51281-0872-4774-8211-76ce4578e524)

[**Option 2**](https://public.flourish.studio/visualisation/17499249/): bars showing average yearly repayments over different periods of time, highlighting how they have increased quite dramatically. We could also just compare 2010-2014 to 2023-25, for example, to further emphasise the massive jump in repayments in the last decade or so.

![image](https://github.com/ONEcampaign/net_flows/assets/7374450/e7b17a8f-6491-4011-8899-20bc42282f45)


I will tackle the China portion once we decide on approach.
@lpicci96 , @Mattie-P, @sharcourt14 thoughts? a preference?

**Comment by jm-rivera** [comment]
This would work much better on the page (and have actual transition text, etc). But here's an idea for how to show the china portion. Thoughts @Mattie-P @lpicci96 ?

https://public.flourish.studio/story/2328827/

**Comment by lpicci96** [comment]
It's a nice clean chart. But honestly I think the scrolly is necessary. It could just be a single chart with annotations/headings. Since we usually see disengagement from scrollies I don't see them adding much value in this page

**Comment by jm-rivera** [comment]
Thanks Luca! 
I think we should see on the page. It's a way to highlight China without overcrowding the main point of the first chart (which is the massive jump in repayments). And we should keep a close eye on stats for a single transition scrolly. It may be that because it's a quick single transition we don't see people dropping off.
