### ISSUE TITLE
1.3 Debt and grants inflows to developing countries

### ISSUE THREAD

**Issue by jm-rivera** [ONEcampaign/net_flows#8]
A chart (or more than one, or grid of charts) which shows the trends in debt and grants inflows.

[This chart](https://observablehq.com/@one-campaign/net-flows#cell-1223) is an example of what the data shows. 

The point of the chart is to unpack what is happening to inflows. The challenge is that the story depends on the group of countries that you are looking at. In some cases, private debt inflows are decreasing. In others it is Chinese debt. In others it may be decreasing aid.

Figuring the best chart in this case may involve looking at the data and seeing which angle is most eloquent of the broader problem. Or it may be about breaking down the issue in different parts. We could also consider scrollytelling if we haven't used it earlier in the paper.

**Comment by lpicci96** [comment]
One idea I have:

Placing these charts consecutively

<img width="793" alt="image" src="https://github.com/ONEcampaign/net_flows/assets/56567716/b45630fa-f7ba-442a-8a13-4f8ca1c28afa">
<img width="793" alt="image" src="https://github.com/ONEcampaign/net_flows/assets/56567716/59887cd9-a68a-4e15-94b1-9ab42edb322c">

**Comment by jm-rivera** [comment]
what's happened to non-concessional lending?

I quite like this approach, though for the second chart I would make the y-range be reflective of the data instead of aligned with the previous chart

**Comment by lpicci96** [comment]
It is a conscious decision to omit non-concessional because the text points to private finance as the cause of the drop and the need for concessional finance to support the need for new financing. So removing additional series may distract.

Also conscious decision to keep the same y range. Otherwise non concessional and grants will appear to have greater fluctuations than actually occurred. I keep the same y scale for comparability with the 1st chart and to emphasise the "stalled" point

**Comment by jm-rivera** [comment]
I see the value in focus only on the data around the argument... But, we should be careful that we're comparing things correctly. 

Countries that can access concessional lending and grants may not be the same as countries that have market access for private debt. So comparing private lending to concessional finance in aggregate form may mean you're comparing data from two different sets of countries, while implying that the money is going to the same places.

Maybe the second chart should be on 'official finance', and be two lines for each bilateral and multilateral: grants and loans. what would the trends show then?

On the point about the y-range I disagree. I think this is not an honest/accurate presentation of the data. If we need to extend the range beyond what's on the data for it to _seem_ like it is stalling, that's a problem. Concessional lending and private lending are on separate scales, and we have different charts. So making them seem small and flat by synchronising the range with other data isn't great... even if it 'emphasises' the point.

Would we say they have 'stalled' if the range reflected the true range in this data? Probably not for bilateral, but likely yes for multilateral. That's useful, since we're making the case for much increased multilateral lending.

**Comment by lpicci96** [comment]
This is another option

<img width="793" alt="image" src="https://github.com/ONEcampaign/net_flows/assets/56567716/cf849a7b-a4ad-45bc-a1e4-032632c0888b">

**Comment by jm-rivera** [comment]
Yes int is an interesting presentation. However, I'd immediately ask why 2019. It feels cherrypicked without more context. Can we see a similar chart (in terms of breakdown) but which shows the time series?

**Comment by lpicci96** [comment]
I don't think it necessarily cherry picking. I'm following what I'm reading in the text which points directly to post pandemic interest rate, China, and attention on Ukraine. I understand this as  "there has been a significant change in the last 4 years". The slope is a way to focus on that argument. 
I think having a clearer story arc at the beginning  would be helpful to design better charts 


<img width="793" alt="image" src="https://github.com/ONEcampaign/net_flows/assets/56567716/e788f87f-769f-4bd8-803e-9f5686bb54e1">

**Comment by jm-rivera** [comment]
yes the full series is less 'clear'.

@sharcourt14 what do you think [of this option](https://github.com/ONEcampaign/net_flows/issues/8#issuecomment-2047103740)? (with a slightly different title about financial markets rather than bondholders)

![image](https://github.com/ONEcampaign/net_flows/assets/7374450/c87da262-0837-4f6d-87fa-3e3c04e7c133)

**Comment by lpicci96** [comment]
as per @sharcourt14 suggestions. here is the final chart

https://public.flourish.studio/visualisation/17518374/

<img width="792" alt="image" src="https://github.com/ONEcampaign/net_flows/assets/56567716/1727fa6f-0dbb-4f82-ad34-cd60551e2fa0">
